name: 'Update the node modules'
description: 'Updates node modules via GitHub Actions.'
author: 'poad <ken-yo@mbr.nifty.com>'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  yarn:
    description: 'When use the yarn, then true'
    default: 'false'
  path:
    description: '.'
    default: './'
  debug:
    description: 'When logging debug level, then true'
    default: 'false'
runs:
  using: 'docker'
  image: './Dockerfile'