name: 'Update the node modules'
description: 'Updates node modules via GitHub Actions.'
author: 'poad <ken-yo@mbr.nifty.com>'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  yarn:
    description: (Optional) When use the yarn, then true
    default: 'false'
  path:
    description: (Optional) path of package.json
    default: './'
  debug:
    description: (Optional) When logging debug level, then true
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/main.js'
